Publications/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.homepage,name='home'),
    path('publication_level/',views.publications_level,name='publication_level'),
    path('publication_level/search',views.search,name='search'),
    path('publication_level/(<int:level_id>)/',views.publications_all,name='publication_article'),
    path('aboutus/',views.aboutus,name='aboutus')
    
]

Researchers_hut/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('Publications.urls','Publications'),namespace='publications')),
    path('user/',include(('users.urls','users'),namespace='users')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include
from users import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('register/',views.registerationPage,name='register'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view, name= 'logout'),
    path('reserchers/',views.reserchers, name='reserchers'),
    path('createpannel/',views.User_pannel_creation,name='createpannel'),
    path('myprofiles/',views.myprofiles,name='myprofiles'),
    path('editprofile/<int:p_id>',views.editprofile,name='editprofile'),
    path('search/',views.searchfunction,name='search'),
    path('delete/<int:d_id>',views.delete,name='delete'),
]

Publications/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Year(models.Model):
    year =  models.IntegerField(validators=[MinValueValidator(2005),MaxValueValidator(2023)],unique=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        y = str(self.year)
        return y
class Field(models.Model):
    level = models.CharField(max_length=15)

    def __str__(self):
        return self.level
class Publication(models.Model):
    year = models.ForeignKey(Year,on_delete = models.CASCADE)
    level = models.ForeignKey(Field,on_delete = models.CASCADE)
    title = models.CharField(max_length=100)
    author = models.TextField()
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'publications'

    def __str__(self) :
        return self.text[:50]
            
            
       
        


    

Publications/views.py
from django.shortcuts import render
from .models import Field
from . models import Year,Publication
from django.http import HttpResponse
# Create your views here.

def homepage(request):
    return render(request,'Publications/index.html')


def publications_level(request):
    level = Field.objects.all()
    year = Year.objects.all()
    context = {'level' : level,'year':year}
    return render(request,'Publications/publication_level.html',context)

def publications_all(request,level_id):
    level = Field.objects.get(id=level_id)
    publications = level.publication_set.order_by('year_id')
    year = Year.objects.all()
    context = {'level':level,'publications':publications,'year':year}
    return render(request,'Publications/publication_articles.html',context)

def search(request):
    author1 = request.GET['author']
    title1 = request.GET['title']
    search_result = Publication.objects.filter(author__icontains=author1)
    if title1 == "":
        search_result = Publication.objects.filter(author__icontains=author1)
    if author1 == "":
        search_result = Publication.objects.filter(title__icontains=title1)
    if title1 != "" and author1 != "":
        search_result = Publication.objects.filter(title__icontains=title1).filter(author__icoontains=author1)   
    context= {'search_result':search_result}
    return render(request,'Publications/search_result.html',context)

def aboutus(request):
    return render(request,'Publications/aboutus.html')

Publications/templates/Publications/aboutus.html
 {% extends "Publications/base.html" %}

{% block content %}


<body class="header">
    <div class="about-section" style="backface-visibility: hidden">
        <h1 style="color: white"><b>About Us</b></h1>
        <h2>SPONSERED BY</h2>
  <h3>HAYAT TECH</h3>
</div>
<h2 style="text-align:center;color: white" >Our Team</h2>

    <div class="row" style="max-width:100%;margin-left:auto;margin-right:auto;">
  <div class="column">
    <div class="card">
      
      <div class="container">
        <h2>Syed Hassan</h2>
        <p class="title">CEO & Founder</p>
        <p>PHONE NUMBER : +92 3359549776</p>
        <p>syedhassan6135@gmail.com</p>
      </div>
    </div>
  </div>
    </div>

    <!--<section class="wrapper header">
    <div class="container-fostrap">
        <div>

            <h1 class="heading" style="color: white">
                OUR TEAM 
            </h1>
        </div>
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-4">
                        <div class="card">
                            <div class="card-content">
                                <h2 class="card-title">
                                    SPONSORED BY
                                    <h3>HAYAT TECH</h3>
                                </h2>
                                <p class="">
                                    Our business specialises in web development, offering our clients dynamic, useful websites.
                                </p>
                            </div>
                            <div class="card-read-more">
                                <a href="http://www.fostrap.com/2016/03/bootstrap-3-carousel-fade-effect.html" class="btn btn-link btn-block">
                                    Read More
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="card">
                            <a class="img-card" href="http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html">
                            <img src="https://3.bp.blogspot.com/-bAsTyYC8U80/VtLZRKN6OlI/AAAAAAAABjY/kAoljiMALkQ/s400/material%2Bnavbar.jpg" />
                          </a>
                            <div class="card-content">
                                <h4 class="card-title">
                                    <a href="http://www.fostrap.com/2016/02/awesome-material-design-responsive-menu.html"> Material Design Responsive Menu
                                  </a>
                                </h4>
                                <p class="">
                                    Material Design is a visual programming language made by Google. Language programming...
                                </p>
                            </div>
                            <div class="card-read-more">
                                <a href="https://codepen.io/wisnust10/full/ZWERZK/" class="btn btn-link btn-block">
                                    Read More
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="card">
                            <a class="img-card" href="http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html">
                            <img src="https://4.bp.blogspot.com/-TDIJ17DfCco/Vtneyc-0t4I/AAAAAAAABmk/aa4AjmCvRck/s1600/cover.jpg" />
                          </a>
                            <div class="card-content">
                                <h4 class="card-title">
                                    <a href="http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html">5  Button Hover Animation Effects
                                  </a>
                                </h4>
                                <p class="">
                                    tutorials button hover animation, although very much a hover button is very beauti...
                                </p>
                            </div>
                            <div class="card-read-more">
                                <a href="http://www.fostrap.com/2016/03/5-button-hover-animation-effects-css3.html" class="btn btn-link btn-block">
                                    Read More
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>-->

</body>
<style>
    body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #474e5d;
  color: white;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}
    .text2{
           backface-visibility: hidden;
            text-align: center;
        color: white
           
    }
@import url(https://fonts.googleapis.com/css?family=Roboto:400,100,900);

html,
body{
  -moz-box-sizing: border-box;
       box-sizing: border-box;
  height: 100%;
  width: 100%; 
  background: #FFF;
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
}
 
.wrapper {
  display: table;
  height: 100%;
  width: 100%;
}

.container-fostrap {
  display: table-cell;
  padding: 1em;
  text-align: center;
  vertical-align: middle;
}
.fostrap-logo {
  width: 100px;
  margin-bottom:15px
}
h1.heading {
  color: #fff;
  font-size: 1.15em;
  font-weight: 900;
  margin: 0 0 0.5em;
  color: #505050;
}
@media (min-width: 450px) {
  h1.heading {
    font-size: 3.55em;
  }
}
@media (min-width: 760px) {
  h1.heading {
    font-size: 3.05em;
  }
}
@media (min-width: 900px) {
  h1.heading {
    font-size: 3.25em;
    margin: 0 0 0.3em;
  }
} 
.card {
  display: block; 
    margin-bottom: 20px;
    line-height: 1.42857143;
    background-color: #fff;
    border-radius: 2px;
    box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12); 
    transition: box-shadow .25s; 
}
.card:hover {
  box-shadow: 0 8px 17px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
}
.img-card {
  width: 100%;
  height:200px;
  border-top-left-radius:2px;
  border-top-right-radius:2px;
  display:block;
    overflow: hidden;
}
.img-card img{
  width: 100%;
  height: 200px;
  object-fit:cover; 
  transition: all .25s ease;
} 
.card-content {
  padding:15px;
  text-align:left;
}
.card-title {
  margin-top:0px;
  font-weight: 700;
  font-size: 1.65em;
}
.card-title a {
  color: #000;
  text-decoration: none !important;
}
.card-read-more {
  border-top: 1px solid #D4D4D4;
}
.card-read-more a {
  text-decoration: none !important;
  padding:10px;
  font-weight:600;
  text-transform: uppercase
}    
    

</style>
{% endblock content %}

Publications/templates/Publications/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta name="viewport" content="with=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        
    
        <title>RESEARCHERS HUT</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    
    
    
        <!--<link rel="stylesheet" href="static/css/style.css">-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;500;600;700&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/f8313cd07e.js" crossorigin="anonymous"></script>

    </head>    


    <nav class="background_image">
       <!-- <a href="index.html"><img src="static/images/logo.png" width="150" height="100"></a>-->
        <div class="nav-links" id="navLinks">
               <i class="fa fa-times" onclick="hideMenu()"></i>
               <ul>
                   {% if user.is_authenticated %}
                   <li><a href="{% url 'publications:home' %}"><h4>User Name: <b>{{user.username}}</b></h4></a></li>
                   
                   <li><a href="{% url 'users:myprofiles' %}"><h4>My Profiles</h4></a></li>
                   
                   <li><a href="{% url 'publications:home' %}"><h4>HOME</h4></a></li>
                   <li><a href="{% url 'users:logout' %}"><h4>LOG OUT</h4></a></li>
                   <li><a href="{% url 'publications:aboutus' %}"><h4>ABOUT</h4></a></li>
                    <li><a href=""><h4>CONTACTS</h4></a></li>
                    {% else %}
                    <li><a href="{% url 'publications:home' %}"><h4>HOME</h4></a></li>
                   <li><a href="{% url 'users:login' %}"><h4>LOG IN</h4></a></li>
                   <li><a href="{% url 'publications:aboutus' %}"><h4>ABOUT</h4></a></li>
                    <li><a href=""><h4>CONTACTS</h4></a></li>
                   {% endif %}
            </ul>
        </div>
          <i class="fa fa-bars" onclick="showMenu()"></i> 
    </nav>
    

<script>
    var navLinks = document.getElementById("navLinks")
    function showMenu(){
        navLinks.style.right = "0";    
    }
        function hideMenu(){
        navLinks.style.right = "-200px";    
    }
       
    </script>
<style>
    .background_image{    height:10px ;
        width: auto;
        background-color: darkblue}
    *{
    margin: 0;
    padding: 0;
 font-family: 'Poppins', sans-serif;
}
.header{
    height: 100vh;
    width: auto;
    background-image: linear-gradient(rgba(4,9,30,0.7),rgba(4,9,30,0.7)),url('/static/images/banner.png'); 
    background-position: center;
    background-size: cover;
    position: relative;
}
nav{
    display: flex;
    padding: 3% 6%;
    justify-content: space-between;
    align-items: center;
}
nav img{
    width: 150px;
}
.nav-links{
    flex: 1;
    text-align: right;
}
.nav-links ul li{
    list-style: none;
    display: inline-block;
    padding: 8px 12px;
    position: relative;
}
.nav-links ul li a{
    color: white;
    text-decoration: none;
}
.nav-links ul li::after{
   content: '';
    width: 0%;
    height: 1px;
    background: #f44336;
    display: block;
    margin: auto;
    transition: 0.5s;
}
.nav-links ul li:hover::after{
    width: 100%;
}
.text-box{
    width: 90%;
    color: white;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
        text-align: center;
}
.text-box h1{
    font-size: 50px;
}
.text-box h2{
    font-size: 40px;
}
.text-box p{
    margin: 10px 0 40px;
    font-size: 16px;
}
.hero-btn{
    display: inline-block;
    text-decoration: none;
    color: #fff;
    border: 1px solid #fff;
    padding: 12px 34px;
    font-size: 25px;
    background: transparent;
    position: relative;
    cursor: pointer;
     border-radius: 30px;
}
.hero-btn:hover{
    border: 1px solid #f44336;
    background: linear-gradient(to right, #ff105f,#ffab06);
    transition: 1s;   
}
nav .fa{
    display: none;
}
@media(max-width: 700px){
    .text-box h1{
        font-size: 20px;
    }
    .text-box h2{
        font-size: 20px;
    }
    .text-box p{
    margin: 10px 0 40px;
    font-size: 10px;
}
        .hero-btn{
    display: inline-block;
    text-decoration: none;
    color: #fff;
    border: 1px solid #fff;
    padding: 12px 34px;
    font-size: 10px;
    background: transparent;
    position: relative;
    cursor: pointer;
    }
    .nav-links ul li{
        display: block;   
    }
    .nav-links{
        position: absolute;
        background: #400000;
        height: 100vh;
        width: 200px;
        top: 0;
        right: -200px;
        text-align: left;
        z-index: 2; 
        transition: .5s;
    }
    nav .fa{
        display: block;
        color:white;
            margin: 10p;
        font-size: 22px;
        cursor: pointer;
    }
    .nav-links ul{
        padding: 30px;
    }
    body {
    height: 100vh;
    width: auto;
    background-image: linear-gradient(rgba(4,9,30,0.7),rgba(4,9,30,0.7)),url('/static/images/banner.png'); 
    background-position: center;
    background-size: cover;
    position: relative;
    }

}






</style>
{% block content %}{% endblock content %}

Publications/templates/Publications/index.html
{% extends "Publications/base.html" %}
<!DOCTYPE html>
{% block content %}
<html>
    <!--<head>
        <meta name="viewport" content="with=device-width, initial-scale=1.0">
        <title>SEHAT FALAH</title>
        <link rel="stylesheet" href="static/css/style.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;500;600;700&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/f8313cd07e.js" crossorigin="anonymous"></script>
    </head>-->
<body class="header">
    <section >
    <!--<nav>
       <!-- <a href="index.html"><img src="static/images/logo.png" width="150" height="100"></a>
           <div class="nav-links" id="navLinks">
               <i class="fa fa-times" onclick="hideMenu()"></i>
               <ul>
        <li><a href="">HOME</a></li>
        <li><a href="">ABOUT</a></li>
        <!--<li><a href="">SERVICES</a></li>
        <li><a href="">CONTACTS</a></li>
               </ul>
        </div>
          <i class="fa fa-bars" onclick="showMenu()"></i> 
        </nav>-->
        <div class="text-box">
<h1>RESEARCHERS HUT</h1>
            <h2>VISION</h2>
            <p>Platforms for collaborative multidisciplinary research are effective tools.
Our vision is to offer a platform for bringing together scholars with different specialties.
          <br>      
<br>1)	They can easily discuss their research topics and work together on this site.
                
<br>2)	By offering this forum, we hope to develop Pakistan's research society. 
            </p>           
            {% if user.is_authenticated %}
            
            
            <a href="{% url 'publications:publication_level' %}"class="hero-btn">PUBLICATIONS</a>
            <br>
            <br>
            <a href="{% url 'users:reserchers' %}"class="hero-btn">RESEARCHERS </a>
            <br>
            <br>
            <a href="{% url 'users:createpannel' %}"class="hero-btn">Create Your Profile </a>
            {% else %}
            <a href="{% url 'publications:publication_level' %}"class="hero-btn">PUBLICATIONS</a>
            <br>
            <br>
            <a href="{% url 'users:login' %}"class="hero-btn">LOG IN</a>
            
            <ul>
                <br>
                <a href="{% url 'users:register' %}"class="hero-btn">JOIN US AS A RESEARCHER</a>
            </ul>
            {% endif %}
        </div>
    
    
  <!-- <script>
    var navLinks = document.getElementById("navLinks")
    function showMenu(){
        navLinks.style.right = "0";    
    }
        function hideMenu(){
        navLinks.style.right = "-200px";    
    }
       
    </script>
<!--<style>
    .backgroung_image{
        background-image: url('static/images/banner.png');
        background-size: cover;
        background-repeat: no-repeat;
        height: 100vh;
        width: auto;
        
    }
    

    
</style>-->

    
    
    
    </section>
    </body>
    
    

{% endblock content %}

Publications/templates/Publications/publication_articles.html
{% extends "Publications/base.html" %}
{% block content %}

<body>
<section class="header">

    {% for article in publications %}
    <div class="panel panel-default">
        <div class="panel-heading"><h4>{{level}}</h4></div>
          <div class="panel-body">
              <p>Author name : <b>{{article.author}}</b></p> 
          </div>
        <div class="panel-body">
            <p>Year Published : <b>{{article.year}}</b></p> 
          </div>
                <div class="panel-body">
                    <p>Title : <b>{{article.title}}</b></p>
          </div>
                <div class="panel-body">
           <p>{{article.text|linebreaks}}</p> 
          </div>
    </div>
    {% endfor %}



</section>
<style>
    #background{
        backface-visibility: hidden;
    }

</style>
<body>
{% endblock content %}

Publications/templates/Publications/publication_level.html
{% extends "Publications/base.html" %}
{% block content %}
<body>
    <section class="header">
          <form method="get" class="navbar-form navbar-left" action="{%  url 'publications:search' %}">
            <div class="form-group">
                <input type="search" class="form-control" aria-label="Search" placeholder="Author" name="author" id="author">
                <input type="search" class="form-control" aria-label="Search" placeholder="Title" name="title" id="title">
            </div>
        <button type="submit" class="btn btn-default"><b>SEARCH</b></button>
    </form>
    <div class="text-box">
        <h1>Publications :</h1>
        <ul style="list-style: none">
            {% for l in level %}
            <li><a href="{% url 'publications:publication_article' l.id %}" ><h3 class="btn">{{l}}</h3></a></li>
            {% endfor %}
        </ul>    
    </div>
           
        
    </section>



</body>
<style>
    .text-colour{            
    color: red;
    }
    .btn{
        display: inline-block;
    text-decoration: none;
    color: #fff;
    border: 2px;
    padding: 12px 34px;
    font-size: 15px;
    background: transparent;
    position: relative;
    cursor: pointer;
     border-radius: 30px;
    }
    .btn:hover{
    border: 1px solid #f44336;
    background: linear-gradient(to right, #ff105f,#ffab06);
    transition: 1s; 
    }
</style>
{% endblock content %}

Publications/templates/Publications/search_result.html
{% extends "Publications/base.html" %}
{% block content %}


<section class="">

    <form method="get" class="navbar-form navbar-left" action="{%  url 'publications:search' %}">
            <div class="form-group">
                <input type="search" class="form-control" aria-label="Search" placeholder="Author" name="author" id="author">
                <input type="search" class="form-control" aria-label="Search" placeholder="Title" name="title" id="title">
            </div>
        <button type="submit" class="btn btn-default"><b>SEARCH</b></button>
    </form>
    <br>
    <br>
    <br>
        <div class="panel panel-default">
            <div class="panel-heading"><h3><b>Search Results</b></h3></div>
        </div>  
    {% for article in search_result %}
  
    <div class="panel panel-default">
        <div class="panel-heading"><h4>{{article.level}}</h4></div>
          <div class="panel-body">
              <p>Author name : <b>{{article.author}}</b></p> 
          </div>
        <div class="panel-body">
            <p>Year Published : <b>{{article.year}}</b></p> 
          </div>
                <div class="panel-body">
                    <p>Title : <b>{{article.title}}</b></p>
          </div>
                <div class="panel-body">
           <p>{{article.text|linebreaks}}</p> 
          </div>
    </div>
    {% endfor %}



</section>
<style>
    #background{
        backface-visibility: hidden;
    }
    .text-colour{            
    color: red;
    }
    .btn{
        display: inline-block;
    text-decoration: none;
    color: #fff;
    border: 2px;
    padding: 12px 34px;
    font-size: 15px;
    background: transparent;
    position: relative;
    cursor: pointer;
     border-radius: 30px;
    }
    .btn:hover{
    border: 1px solid #f44336;
    background: linear-gradient(to right, #ff105f,#ffab06);
    transition: 1s; 
    }
</style>


{% endblock content %}