Researchers_hut/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('Publications.urls','Publications'),namespace='publications')),
    path('user/',include(('users.urls','users'),namespace='users')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include
from users import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('register/',views.registerationPage,name='register'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view, name= 'logout'),
    path('reserchers/',views.reserchers, name='reserchers'),
    path('createpannel/',views.User_pannel_creation,name='createpannel'),
    path('myprofiles/',views.myprofiles,name='myprofiles'),
    path('editprofile/<int:p_id>',views.editprofile,name='editprofile'),
    path('search/',views.searchfunction,name='search'),
    path('delete/<int:d_id>',views.delete,name='delete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField

class UserPannel(models.Model):
    FIELD_CHOICES = [
        ('ENGINEERING','ENGINEERING'),
        ('MEDICAL','MEDICAL')
    ]
    
    GENDER_CHOICES = [
        ('MALE','MALE'),
        ('FEMALE','FEMALE')
    ]

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100,blank=False)
    group = models.CharField(max_length=50,choices=FIELD_CHOICES )
    gender = models.CharField(max_length=10,choices=GENDER_CHOICES)
    phone = PhoneNumberField(blank=True,null=True)
    profile_pic = models.ImageField( upload_to="myimage",null=True,blank=True,default='/usericon.png/')
    college = models.CharField(max_length=50)
    programe = models.CharField(max_length=200)
    level = models.CharField(max_length=200)
    topic = models.CharField(max_length=300)
    description = models.TextField(max_length=1000)
    submitted = models.DateTimeField(auto_now_add=True)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import UserPannel
# phone number
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget



# USER MODEL
from django.contrib.auth import get_user_model
User = get_user_model()
#

class CreatUserForm(UserCreationForm):



    def __init__(self, *args , **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'type':"text",
            'class':"form-control",
            'name':"username",
            'id':"username",
            'placeholder':"Enter your Username with out SPACES",
        })
        self.fields['email'].widget.attrs.update({
            ' type':"text",
            'class':"form-control",
            'name':"email",
            'id':"email",
            ' placeholder':"Enter your Email",
        })
        self.fields['password1'].widget.attrs.update({
            ' type':"password",
            'class':"form-control",
            'name':"password",
            'id':"password",
            ' placeholder':"Enter your Password",
        })
        self.fields['password2'].widget.attrs.update({
            ' type':"password",
            'class':"form-control",
            'name':"confirm",
            'id':"confirm",
            ' placeholder':"Confirm your Password",
        })
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

        ''' widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'password1': forms.TextInput(attrs={'class':'form-control'}),
            'password2': forms.TextInput(attrs={'class':'form-control'}),
        }'''  

class UserPannelForm(forms.ModelForm): 
    phone = PhoneNumberField(
        widget=PhoneNumberPrefixWidget(initial='PK')

    )

    def __init__(self, *args , **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class':"form-control",
            'placeholder':"Enter Your Name"
        })
        self.fields['gender'].widget.attrs.update({
            'class':"form-control",
        })
        self.fields['phone'].widget.attrs.update({
            'class':"form-control",
            'placeholder':"Enter Your Phone Number default = 03000000000"
        })    
        self.fields['group'].widget.attrs.update({
            'class':"form-control",
        })
        self.fields['college'].widget.attrs.update({
            'class':"form-control",
            'placeholder':'Name of INSTITUTION'
        })
        self.fields['programe'].widget.attrs.update({
            'class':"form-control",
            'placeholder':"BS Programe"
        })
        self.fields['level'].widget.attrs.update({
            'class':"form-control",
            'placeholder':"Year"
        })
        self.fields['topic'].widget.attrs.update({
            'class':"form-control",
            'placeholder':"Research Topic"
        })
        self.fields['profile_pic'].widget.attrs.update({
            'class':"form-control",
        })
        self.fields['description'].widget.attrs.update({
            'class':"form-control",
        })    
    class Meta:
        model = UserPannel
        fields = ['name','gender','phone','group','college','programe','level','topic','profile_pic','description']
        wedgets = {'description':forms.Textarea(attrs={'cols' : 30})}

users/views.py
from django.shortcuts import render,HttpResponse , HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreatUserForm , UserPannelForm
#from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate 
from django.urls import reverse
from .models import UserPannel
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

from django.contrib.auth import get_user_model
User = get_user_model()

from django.contrib import messages

def registerationPage(request):
    #if request.method == "POST":
    #    uname = request.POST.get('username')                               help   
    #    email = request.POST.get('email')                                  help   
    #    pass1 = request.POST.get('password')                               help
    #    pass2 = request.POST.get('confirm')                                help    
    #    my_user = User.objects.create_user(uname,email,pass1)              help
    #    my_user.save()
    #    return HttpResponse('Usr has been created'  
    if request.method != 'POST':
        form = CreatUserForm()
    else:
        form = CreatUserForm(request.POST)
        if form.is_valid:
            new_user = form.save()
            authenticate_user = authenticate(username = new_user.email,password=request.POST['password1'])
            login(request,authenticate_user)
            return HttpResponseRedirect(reverse('users:createpannel'))
            
            
    context= {'form':form,}
    return render(request,'users/register2.html',context)
   
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('publications:home')) 

def login_view(request):
    logout(request)
    if request.method == 'POST':
        uname = request.POST.get('username') 
        passwor = request.POST.get('password')
        user = authenticate(username=uname,password=passwor)
        login(request,user)
        return HttpResponseRedirect(reverse('publications:home'))       

    return render(request,'users/login.html')

@login_required
def reserchers(request):
    resercher = UserPannel.objects.all()
    context = {'resercher':resercher}
    return render(request,'users/finalpannel.html',context)

    
@login_required  
def User_pannel_creation(request):
    '''Add a new topic'''
    # get from the browser
    if request.method != 'POST':
        # NO DATA SUBMITTED CREAT A BLANK FORM
        form = UserPannelForm()
    # post method    
    else:
        #POST DATA SUBMITED ; PROCESS DATA
        form = UserPannelForm(request.POST,request.FILES)
        if form.is_valid():
            
            user_pannel = form.save(commit=False)
            user_pannel.owner = request.user
           
            user_pannel.save()
            return HttpResponseRedirect(reverse('users:reserchers'))

    context = {'form' : form}
    return render(request,'users/User_pannel.html',context)         

@login_required
def myprofiles(request):
    myprofiles = UserPannel.objects.filter(owner=request.user)
    context = {'myprofiles':myprofiles}
    return render(request,'users/myprofiles.html',context)
@login_required
def delete(request, d_id):
    pannel = UserPannel.objects.get(id=d_id)
    if pannel.owner != request.user:
        raise Http404    
    
    if request.POST['yes'] == 'YES':
        pannel.delete()
        return HttpResponseRedirect(reverse('users:myprofiles'))
    context= {'r':pannel}    
    return render(request,'users/delete.html',context)



@login_required
def editprofile(request, p_id):
    pannel = UserPannel.objects.get(id=p_id)
    owner = pannel.owner
    if request.method != 'POST':
        form = UserPannelForm(instance=pannel)
    else:
        request.POST and request.FILES
        form = UserPannelForm(request.POST or None , request.FILES or None,instance=pannel)
        if form.is_valid():
            print(form.changed_data['name'])
            form.save()
            return HttpResponseRedirect(reverse('users:myprofiles'))    
        if pannel.owner != request.user:
            raise Http404
    #pannel = UserPannel.objects.get(id=p_id)
    #owner = pannel.owner
    #form = UserPannelForm(request.POST or None,request.FILES or None, instance=pannel)
    #if form.is_valid():
    #    form.save()
    #    return HttpResponseRedirect(reverse('users:myprofiles'))
    #if pannel.owner != request.user:
    #    raise Http404    
    context = {
        'form':form,
        'pannel':pannel,
        'owner':owner.username
    }
    return render(request, 'users/editpannel.html',context)       

def searchfunction(request):
    gender = request.GET['gender']
    field = request.GET['field']
    programme=request.GET['BS']
    college1 = request.GET['college']
    if gender == 'ANY':
        search_result_g_f = UserPannel.objects.filter(group=field)
    else:
        search_result_g_f = UserPannel.objects.filter(gender=gender).filter(group=field)
    if programme == '':
       final_result = search_result_g_f.filter(college__icontains=college1)
    if college1 == '':
       final_result = search_result_g_f.filter(programe__icontains=programme)
    if programme != '' and college1 != '':
        final_result = search_result_g_f.filter(programe__icontains=programme).filter(college__icontains=college1)   

    print(gender,field,programme,college1 )
    context = {'result': final_result}
    return render(request,'users/search.html',context)

users/templates/users/User_pannel.html
{% extends "Publications/base.html" %}
{% block content %}
<body class="header">
<form class="form-horizontal" method="post" action="{% url 'users:createpannel' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container text3">
    <div class="row justify-content-center">
        <div class="col-md-8 text2" >
            <div class="card">
    <br>
                
    <div><label class="text2"><h5>NAME</h5></label>
    {{form.name}}</div>
    
    <div><label class="text2"><h5>Gender</h5></label>
    {{form.gender}}</div>
    
    <div><label class="text2"><h5>Phone Number</h5></label>
    {{form.phone}}</div>
    
    <div><label class="text2"><h5>Group</h5></label>
    {{form.group}}</div>
    
    <div><label class="text2"><h5>Institution</h5></label>
    {{form.college}}</div>
    
    <div><label class="text2"><h5>BS PROGRAMME</h5></label>
    {{form.programe}}</div>
    <div><label class="text2"><h5>Year</h5></label>
    {{form.level}}</div>
    
    <div><label class="text2"><h5>Research Topic</h5></label>
    {{form.topic}}</div>
    <div><label class="text2"><h5>Image</h5></label>
    {{form.profile_pic}}</div>    
    <div><label class="text2"><h5>Description</h5></label>
    {{form.description}}</div>
    <br>
    <br>
    <div class="form-group ">
                                       
        <button name="submit"  class="btn btn-primary btn-lg btn-block login-button">Register</button>
                
       
            </div>
            </div>
        </div>        
    </div>
    </div>    
    </form> 
</body>    


<style>
    .text2{
            width: 40;
            color: white;
            text-align: center;
    }
    .text3{
        align-items: center;
    }
    </style>
{% endblock content %}

users/templates/users/delete.html
 {% extends "Publications/base.html" %}

{% block content %}


<body class="header">

    <br>
    <br>
    <br>
    <br>
<div class="panel panel-default text2" style="max-width:700px;margin-left:auto;margin-right:auto;"s>
  <!-- Default panel contents -->
    <div class="panel-heading">
        {% if r.profile_pic %}
        <img src="{{r.profile_pic.url}}" class="img-rounded" alt="Cinque Terre" width="150" height="150">

        {% else %}
        <div class="panel-heading">
        
        <img src="/static/images/usericon.jpg" class="img-rounded" alt="Cinque Terre" width="150" height="150">
        </div>
        {% endif %}
      </div>
        <div class="panel-heading"><h3 class="card-title">
        Name : <b>{{r.name}}</b>
      </h3></div>
  <!-- List group -->
  <ul class="list-group">
            
                <li class="list-group-item"><h4>Gender : <b>{{r.gender}}</b></h4></li>
      
                <li class="list-group-item"><h4>Group : <b>{{r.group}}</b></h4></li>
                
                <li class="list-group-item"><h4>University: <b>{{r.college}}</b></h4></li>
      
                <li class="list-group-item"><h4>Programme :<B>{{r.programe}}</B></h4><br> {{r.level}}</li>
                
                <li class="list-group-item"> <h4>Reserch Topic: <B>{{r.topic}}</B></h4></li>
                    
                <li class="list-group-item"><p class="">{{r.description}}</p></li>
                
                
      <li class="list-group-item"><h4><h4><b>CONTACT</b></h4> <B>EMAIL : {{r.owner.email}}</B></h4><h5>PHONE : {{r.phone}}</h5></li>
      
      
      <li class="list-group-item"><h4><h5>last login :</h5> <B>{{r.owner.last_login}}</B></h4></li>
      
      <li class="list-group-item"><a href="{% url 'users:editprofile' r.id  %}">EDIT PROFILE</a> </li>
      <li class="list-group-item">
        <form method="post" action="{% url 'users:delete' r.id %}">
                    {% csrf_token %}
            <label><h4>ARE YOU SURE YOU WANT TO <b>DELETE</b></h4></label>
                <input type="submit" class="btn btn-lg btn-danger" value="YES" name="yes">  
        </form>
      
      </li>
      
  </ul>

</div>
</body>
<style>
        .text2{
           backface-visibility: hidden;
            text-align: center;
           
    }</style>

{% endblock content %}

users/templates/users/finalpannel.html
 {% extends "Publications/base.html" %}

{% block content %}


<body class="header">
    
    <form method="get" action="{% url 'users:search' %}" class="navbar-form navbar-left">
        <div class="form-group">
                      
                        <select id="company" class="form-control" name=gender>
                          <option>ANY</option>                            
                          <option>MALE</option>
                          <option>FEMALE</option>
                        </select> 
                      
                
                      
                        <select id="company" class="form-control" name=field>
                          <option>ENGINEERING</option>
                          <option>MEDICAL</option>
                        </select>
        </div>   
            <br>
        
    
            <div class="form-group">
                <input type="search" class="form-control" aria-label="Search" placeholder="BS PROGRAMME" name="BS" id="author" >
                
            
                <input type="search" class="form-control" aria-label="Search" placeholder="College Name" name="college" id="title">
            </div>
        
        <button type="submit" class="btn btn-default"><b>SEARCH</b></button>
</form>
    <br>
    
    
    {% for r in resercher %}
    <br>
    <br>
    <br>
    <br>
<div class="panel panel-default text2" style="max-width:700px;margin-left:auto;margin-right:auto;">
  <!-- Default panel contents -->
        {% if r.profile_pic %}
        <div class="panel-heading">
        
        <img src="{{r.profile_pic.url}}" class="img-rounded" alt="Cinque Terre" width="150" height="150">
        </div>
        {% else %}
    
        <div class="panel-heading">
        
        <img src="/static/images/usericon.jpg" class="img-rounded"  width="150" height="150">
        </div>
        {% endif %}
    
        <div class="panel-heading"><h3 class="card-title">
        Name : <b>{{r.name}}</b>
      </h3></div>
  <!-- List group -->
  <ul class="list-group">
            
                <li class="list-group-item"><h4>Gender : <b>{{r.gender}}</b></h4></li>
      
                <li class="list-group-item"><h4>Group : <b>{{r.group}}</b></h4></li>
                
                <li class="list-group-item"><h4>University: <b>{{r.college}}</b></h4></li>
      
                <li class="list-group-item"><h4>Programme :<B>{{r.programe}}</B></h4><br> {{r.level}}</li>
                
                <li class="list-group-item"> <h4>Reserch Topic: <B>{{r.topic}}</B></h4></li>
                    
                <li class="list-group-item"><p class="">{{r.description}}</p></li>
                
                
      <li class="list-group-item"><h4><h4><b>CONTACT</b></h4> <B>EMAIL : {{r.owner.email}}</B></h4><h5>PHONE : {{r.phone}}</h5></li>
      
      
      <li class="list-group-item"><h4><h5>last login :</h5> <B>{{r.owner.last_login}}</B></h4></li>
      
      
  </ul>

</div>
        <br>
    <br>
     {% endfor %}
    
    
    
</body>
<style>
        .text2{
           backface-visibility: hidden;
            text-align: center;
           
    }</style>

{% endblock content %}

users/templates/users/login.html
{% extends "Publications/base.html" %}
{% block content %}

<body class="header">
    
    <div class="container text2">
<div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header"><FONT COLOR="#ffffff"><h2><b>LOG IN</b></h2></FONT></div>
                            <div class="card-body">

                                <form action="{% url 'users:login' %}" method="post" class="form-horizontal"  >
                                    {% csrf_token %}

                                    <!--<div class="form-group">
                                        <label for="name" class="cols-sm-2 control-label">Your Name</label>
                                        <div class="cols-sm-10">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                                                <input type="text" class="form-control" name="name" id="name" placeholder="Enter your Name">
                                            </div>
                                        </div>
                                    </div>-->
                                    
                                    <div class="form-group">
                                        <label for="username" class="cols-sm-2 control-label"><FONT COLOR="#ffffff"><b>Email</b></FONT></label>
                                        <div class="cols-sm-10">
                                            <div class="input-group">
                                               <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                                                
                                                <input type="text"  class="form-control" name="username" id="username" placeholder="Enter your Username">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="password" class="cols-sm-2 control-label"><FONT COLOR="#ffffff"><b>Password</b></FONT></label>
                                        <div class="cols-sm-10">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                                                
                                                <input type="password" class="form-control" name="password" id="password" placeholder="Enter your Password">
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="form-group ">
                                       
                                        <button name="submit"  class="btn btn-primary btn-lg btn-block login-button">Log In</button>
                
                                    </div>
                                    <div class="login-register">
                                        <a href="{% url 'users:register' %}">REGISTER</a>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
</div>	<script type="text/javascript">
		</script>


</body>
 <style>
    .text2{
            width: 70%;
            color: black;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
            text-align: center;
            
        }
</style>   




{% endblock content %}

users/templates/users/myprofiles.html
 {% extends "Publications/base.html" %}

{% block content %}


<body class="header">
    {% for r in myprofiles %}
    <br>
    <br>
    <br>
    <br>
<div class="panel panel-default text2" style="max-width:700px;margin-left:auto;margin-right:auto;"s>
  <!-- Default panel contents -->
    <div class="panel-heading">
        {% if r.profile_pic %}
        <img src="{{r.profile_pic.url}}" class="img-rounded" alt="Cinque Terre" width="150" height="150">
        {% else %}
    
        <div class="panel-heading">
        
        <img src="/static/images/usericon.jpg" class="img-rounded" alt="Cinque Terre" width="150" height="150">
        </div>
        {% endif %}
      </div>
        <div class="panel-heading"><h3 class="card-title">
        Name : <b>{{r.name}}</b>
      </h3></div>
  <!-- List group -->
  <ul class="list-group">
            
                <li class="list-group-item"><h4>Gender : <b>{{r.gender}}</b></h4></li>
      
                <li class="list-group-item"><h4>Group : <b>{{r.group}}</b></h4></li>
                
                <li class="list-group-item"><h4>University: <b>{{r.college}}</b></h4></li>
      
                <li class="list-group-item"><h4>Programme :<B>{{r.programe}}</B></h4><br> {{r.level}}</li>
                
                <li class="list-group-item"> <h4>Reserch Topic: <B>{{r.topic}}</B></h4></li>
                    
                <li class="list-group-item"><p class="">{{r.description}}</p></li>
                
                
      <li class="list-group-item"><h4><h4><b>CONTACT</b></h4> <B>EMAIL : {{r.owner.email}}</B></h4><h5>PHONE : {{r.phone}}</h5></li>
      
      
      <li class="list-group-item"><h4><h5>last login :</h5> <B>{{r.owner.last_login}}</B></h4></li>
      
      <li class="list-group-item"><a href="{% url 'users:editprofile' r.id  %}">EDIT PROFILE</a> </li>
      <li class="list-group-item">
        <form method="post" action="{% url 'users:delete' r.id %}">
                    {% csrf_token %}
                <input type="submit" class="btn btn-lg btn-danger" placeholder="DELETE" value="DELETE" name="yes">  
        </form>
      
      </li>
      
      
      
  </ul>

</div>
        <br>
    <br>
     {% endfor %}
    
    
    
</body>
<style>
        .text2{
           backface-visibility: hidden;
            text-align: center;
           
    }</style>

{% endblock content %}

users/templates/users/register2.html
{% extends "Publications/base.html" %}
{% block content %}

  <!--{{form.as_p}}-->

   <!-- {% csrf_token %}
        {{form.username.label}}
        {{form.username}}
        
        {{form.email.label}}
        {{form.email}}
    
        {{form.password1.label}}
        {{form.password1}}
    
        {{form.password2.label}}
        {{form.password2}}-->

<body class="header">
    <div class="alert alert-info" role="alert">1) Please Use a UNIQUE : <b>USERNAME and VALID EMAIL </b><br>2) DONOT use Space in User Name</div>
    
    <div class="container text2">
<div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header"><FONT COLOR="#ffffff"><h2><b>Register</b></h2></FONT></div>
                            <div class="card-body">

                                <form action="{% url 'users:register' %}" method="post" class="form-horizontal"  >
                                    {% csrf_token %}

                                    <!--<div class="form-group">
                                        <label for="name" class="cols-sm-2 control-label">Your Name</label>
                                        <div class="cols-sm-10">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                                                <input type="text" class="form-control" name="name" id="name" placeholder="Enter your Name">
                                            </div>
                                        </div>
                                    </div>-->
                                    
                                    <div class="form-group">
                                        <label for="username" class="cols-sm-2 control-label"><FONT COLOR="#ffffff"><b>Username</b></FONT></label>
                                        <div class="cols-sm-10">
                                            <div class="input-group">
                                               <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                                                
                                                  {{form.username}}
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                    <div class="form-group">
                                        <label for="email" class="cols-sm-2 control-label"><FONT COLOR="#ffffff"><b>Your Email</b></FONT></label>
                                        <div class="cols-sm-10">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                                                {{form.email}}
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="password" class="cols-sm-2 control-label"><FONT COLOR="#ffffff"><b>Password</b></FONT></label>
                                        <div class="cols-sm-10">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                                                    {{form.password1}}
                                               
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="confirm" class="cols-sm-2 control-label"><FONT COLOR="#ffffff"><b>Confirm Password</b></FONT></label>
                                        <div class="cols-sm-10">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                                                
                                                {{form.password2}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group ">
                                       
                                        <button name="submit"  class="btn btn-primary btn-lg btn-block login-button">Register</button>
                
                                    </div>
                                    <div class="login-register">
                                        <a href="{% url 'users:login' %}">Login</a>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
</div>	
    <script type="text/javascript">
		</script>


</body>

{% endblock content %}